#!/usr/bin/env bash
# Build log4j-api + log4j-core with plain javac, no Maven, no network.
#
# Why this exists: every Maven repository host is blocked by this environment's
# egress policy, so dependency resolution is impossible. But log4j-api's only
# deps are `provided` (annotations), and every log4j-core dep except log4j-api
# is `optional` -- so the core logging path has no mandatory third-party code.
# We stub the annotations/OSGi API and skip the optional-dependency appenders.
set -uo pipefail

SRC="$(cd "$(dirname "$0")/.." && pwd)"
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/out"
LOG="$HERE/logs"
rm -rf "$OUT" "$LOG"; mkdir -p "$OUT"/{stubs,api,core} "$LOG"

JAVAC_OPTS="-nowarn -encoding UTF-8 -proc:none"

step() { printf '\n\033[1m== %s\033[0m\n' "$1"; }

# ---------------------------------------------------------------- 1. stubs
step "1/5  compiling annotation + OSGi stubs"
find "$HERE/stubs" -name '*.java' > "$LOG/stubs.txt"
javac $JAVAC_OPTS -d "$OUT/stubs" @"$LOG/stubs.txt" 2> "$LOG/stubs.err" \
  && echo "   ok  ($(find "$OUT/stubs" -name '*.class' | wc -l) classes)" \
  || { echo "   FAILED"; tail -30 "$LOG/stubs.err"; exit 1; }

# ---------------------------------------------------------------- 2. api
step "2/5  compiling log4j-api"
find "$SRC/log4j-api/src/main/java" -name '*.java' \
  ! -name 'module-info.java' > "$LOG/api.txt"
echo "   sources: $(wc -l < "$LOG/api.txt")"
javac $JAVAC_OPTS -cp "$OUT/stubs" -d "$OUT/api" @"$LOG/api.txt" 2> "$LOG/api.err" \
  && echo "   ok  ($(find "$OUT/api" -name '*.class' | wc -l) classes)" \
  || { echo "   FAILED"; grep -c 'error:' "$LOG/api.err"; head -40 "$LOG/api.err"; exit 1; }
cp -r "$SRC/log4j-api/src/main/resources/." "$OUT/api/" 2>/dev/null

# ---------------------------------------------------------------- 3. core
# Exclude sources needing optional deps (Kafka, JMS, Jackson, Disruptor, CSV,
# Compress, ZeroMQ, mail) plus the OSGi bundle-activator integration classes.
step "3/5  compiling log4j-core (optional-dependency appenders excluded)"
# Excluded = needs a genuinely absent third-party library (Jackson, JMS, mail,
# Kafka, ZeroMQ, CSV, MongoDB/JDBC). Everything else -- including the whole
# async package and ZipCompressAction (java.util.zip only) -- is compiled.
find "$SRC/log4j-core/src/main/java" -name '*.java' ! -name 'module-info.java' \
  | grep -vE '/core/(jackson|parser)/' \
  | grep -vE '/appender/(mom|nosql|db)/' \
  | grep -vE '/(JsonLayout|YamlLayout|AbstractJacksonLayout|XmlLayout|JacksonFactory)\.java$' \
  | grep -vE '/(YamlConfiguration|YamlConfigurationFactory|JsonConfiguration|JsonConfigurationFactory)\.java$' \
  | grep -vE '/(CsvParameterLayout|CsvLogEventLayout|AbstractCsvLayout)\.java$' \
  | grep -vE '/(SmtpAppender|SmtpManager|MailManager|MimeMessageBuilder)\.java$' \
  | grep -vE '/MutableThreadContextMapFilter\.java$' \
  | grep -vE '/(DisruptorBlockingQueueFactory|JCToolsBlockingQueueFactory)\.java$' \
  | grep -vE '/(MailManagerFactory|GelfLayout)\.java$' \
  | grep -vE '/core/osgi/' \
  > "$LOG/core.txt"
echo "   sources: $(wc -l < "$LOG/core.txt")"
javac $JAVAC_OPTS -cp "$OUT/stubs:$OUT/api" -d "$OUT/core" @"$LOG/core.txt" 2> "$LOG/core.err"
if [ $? -ne 0 ]; then
  echo "   errors: $(grep -c 'error:' "$LOG/core.err")"
  echo "   --- distinct missing symbols ---"
  grep -oE 'package [a-z0-9.]+ does not exist|cannot find symbol' "$LOG/core.err" | sort | uniq -c | sort -rn | head -20
  echo "   --- first failing files ---"
  grep -oE '^/[^:]+\.java' "$LOG/core.err" | sort -u | head -25
  exit 1
fi
echo "   ok  ($(find "$OUT/core" -name '*.class' | wc -l) classes)"
cp -r "$SRC/log4j-core/src/main/resources/." "$OUT/core/" 2>/dev/null

# ------------------------------------------------- 4. plugin descriptor
# Log4j finds its plugins via Log4j2Plugins.dat, normally generated by
# PluginProcessor during the Maven build. PluginProcessor lives in log4j-core
# itself, so re-run javac with it enabled now that core is compiled.
step "4/5  generating Log4j2Plugins.dat via PluginProcessor"
javac -nowarn -encoding UTF-8 -cp "$OUT/stubs:$OUT/api:$OUT/core" \
      -processorpath "$OUT/core:$OUT/api:$OUT/stubs" \
      -processor org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor \
      -d "$OUT/core" @"$LOG/core.txt" 2> "$LOG/plugins.err"
DAT="$OUT/core/META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat"
[ -f "$DAT" ] && echo "   ok  descriptor $(stat -c%s "$DAT") bytes" \
              || { echo "   FAILED - no descriptor"; tail -20 "$LOG/plugins.err"; exit 1; }

# ------------------------------------------------- 5. service registrations
step "5/5  generating META-INF/services from @ServiceProvider"
python3 "$HERE/gen-services.py" "$SRC/log4j-api/src/main/java" "$OUT/api" || exit 1
python3 "$HERE/gen-services.py" "$SRC/log4j-core/src/main/java" "$OUT/core" || exit 1

printf '\n\033[1;32mBUILD OK\033[0m  classpath: %s\n' "$OUT/api:$OUT/core"
